### ISSUE TITLE
Change default schema for mydbr user

### ISSUE THREAD

**Issue by JoeyAlvarez** [JoeyAlvarez/Vote#3]
Make the default schema for the mydbr user the "vote" schema on the database "Vote"

USE yourDatabase;
ALTER USER [yourUser] WITH DEFAULT_SCHEMA = myschema;

**Comment by JoeyAlvarez** [comment]
You can mark this as won't do because its impossible without changing the permissions.

**Comment by Antnknee** [comment]
Attempted default schema change, was not possible.
